// resources/js/Components/TextInput.vue
<script lang="ts" setup>
import { onMounted, ref } from 'vue';

defineProps<{
    modelValue: string;
}>();

defineEmits(['update:modelValue']);

const input = ref<HTMLInputElement | null>(null);

onMounted(() => {
    if (input.value?.hasAttribute('autofocus')) {
        input.value?.focus();
    }
});

defineExpose({ focus: () => input.value?.focus() });
</script>

<template>
    <input
        ref="input"
        :value="modelValue"
        class="border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm"
        @input="
            $emit(
                'update:modelValue',
                ($event.target as HTMLInputElement).value,
            )
        "
    />
</template>

// resources/js/Components/TextInput.tsx
import {
	forwardRef,
	useEffect,
	useImperativeHandle,
	useRef,
	InputHTMLAttributes,
} from "react";

export default forwardRef(function TextInput(
	{
		type = "text",
		className = "",
		isFocused = false,
		...props
	}: InputHTMLAttributes<HTMLInputElement> & { isFocused?: boolean },
	ref,
) {
	const localRef = useRef<HTMLInputElement>(null);

	useImperativeHandle(ref, () => ({
		focus: () => localRef.current?.focus(),
	}));

	useEffect(() => {
		if (isFocused) {
			localRef.current?.focus();
		}
	}, []);

	return (
		<input
			{...props}
			type={type}
			className={
				"rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 " +
				className
			}
			ref={localRef}
		/>
	);
});
